steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
         'deploy',
         'streaming',
         '--trigger-bucket=gs://ab-scanner-dev-files-source-dm',
         '--runtime=python37',
         '--source=./functions/ingest_file',
         '--stage-bucket=gs://ab-scanner-dev-functions-dm',
         '--entry-point=ingest_file',
         '--timeout=540',
         '--region=europe-west2',
         '--project=ab-scanner-dev'
  ]
