steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
         'deploy',
         'streaming_error',
         '--source=./functions/ingest_file',
         '--entry-point=move_file',
         '--timeout=540',
         '--runtime=python37',
         '--stage-bucket=gs://ab-scanner-dev-functions-dm',
         '--trigger-topic=streaming_error_topic',
         '--region=europe-west2',
         '--project=ab-scanner-dev',
         '--set-env-vars SOURCE_BUCKET=gs://ab-scanner-dev-files-source-dm,DESTINATION_BUCKET=gs://ab-scanner-dev-files-error-dm'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
         'deploy',
         'streaming_success',
         '--source=./functions/ingest_file',
         '--entry-point=move_file',
         '--timeout=540',
         '--runtime=python37',
         '--stage-bucket=gs://ab-scanner-dev-functions-dm',
         '--trigger-topic=streaming_success_topic',
         '--region=europe-west2',
         '--project=ab-scanner-dev',
         '--set-env-vars SOURCE_BUCKET=gs://ab-scanner-dev-files-source-dm,DESTINATION_BUCKET=gs://ab-scanner-dev-files-success-dm'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
         'deploy',
         'streaming',
         '--trigger-bucket=gs://ab-scanner-dev-files-source-dm',
         '--runtime=python37',
         '--source=./functions/ingest_file',
         '--stage-bucket=gs://ab-scanner-dev-functions-dm',
         '--entry-point=ingest_file',
         '--timeout=540',
         '--region=europe-west2',
         '--project=ab-scanner-dev'
  ]
